name: Documentation workflow (legacy)

# The event triggers are configured as following:
# - on branch main, trigger the workflow on every push
# - on any pull request, trigger the workflow
# This is to avoid running the workflow twice on pull requests.
on:
  push:
    branches:
      - legacy-docs

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    # https://github.com/bahmutov/cypress-gh-action-split-install/blob/ca3916d4e7240ebdc337825d2d78eb354855464b/.github/workflows/tests.yml#L8-L11
    env:
      # prevents extra Cypress installation progress messages
      CI: 1
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
      # default to being a preview deployment
      DEPLOY_DOCS_ENV: Preview

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v3
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-yarn-legacy-docs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-legacy-docs-

      - name: Set custom Yarn cache path
        run: yarn config set cacheFolder .cache/yarn

      - name: Install dependencies
        run: yarn install --immutable
        env:
          # https://github.com/bahmutov/cypress-gh-action-split-install/blob/ca3916d4e7240ebdc337825d2d78eb354855464b/.github/workflows/tests.yml#L14-L18
          # https://github.com/marketplace/actions/cypress-io#custom-install
          CYPRESS_INSTALL_BINARY: 0

      - name: Building docs website
        run: yarn build:website

      - name: Initialize GitHub Deployment
        uses: bobheadxi/deployments@v1.1.0
        id: start-deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.DEPLOY_DOCS_ENV }}
          ref: ${{ github.head_ref }}

      - name: Deploy to Vercel
        id: deploy-docs-to-vercel-preview
        uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scope: commercetools
          vercel-project-name: merchant-center-application-kit
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DOCS }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID_DOCS }}
          vercel-token: ${{ secrets.VERCEL_TOKEN_DOCS }}
          # there are length restrictions to domains and only *.commercetools.vercel.app works
          # reliably for generated subdomains. No branch name domain because branch names can be long.
          alias-domains: mc-custom-applications-legacy.commercetools.vercel.app

      - name: Update GitHub Deployment Status
        uses: bobheadxi/deployments@v1.1.0
        id: finish_deployment
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.start-deployment.outputs.env }}
          env_url: ${{ steps.deploy-docs-to-vercel-preview.outputs.preview-url }}
          deployment_id: ${{ steps.start-deployment.outputs.deployment_id }}
